config/routes.rb
Rails.application.routes.draw do

   root 'import#index'

     get 'import' => 'import#import', as: :import
     get 'import/status' => 'import#status', as: :import_status

end

app/models/import.rb
class Import < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/import_controller.rb
require 'csv'
class ImportController < ApplicationController

  def index

  end

  def import
    status = Status.first
    status.update_attributes({state: 'Offline', records: 0})

    filepath = "public/import.csv"
    Resque.enqueue(Importer, filepath)
  end

  def status
    render json: Status.first, status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/import/import.html.erb
We're working on it.  You can leave it you want.
<img src="/images/waiting.gif" />
<img src="/images/happy.gif" />

app/views/import/index.html.erb
<h2>Parcel Explorer - v.01</h2>

This little app imports data from a CSV file to the Database.<br/><br/>
The CSV file is found at public/import.csv<br/><br>
<hr/>
<b>WARNING:</b> It takes a LONG time.  Just wait.<br/><br/>
You may <a href="<%= import_path %>">click here</a> to Import<br/><br/>

You could also run "rake parcel:import" from the application directory.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>